from email.message import EmailMessage
message = EmailMessage()
print(message)

sender = "me@example.com"
recipient = "you@example.com"

message['From'] = sender
message['To'] = recipient
print(message)

message['Subject'] = 'Greetings from {} to {}!'.format(sender, recipient)
print(message)

body = """Hey there! ... ... I'm learning to send emails using Python!"""
message.set_content(body)
print(message)

import os.path
attachment_path = "/tmp/example.png"
ttachment_filename = os.path.basename(attachment_path)
import mimetypes
mime_type, _ = mimetypes.guess_type(attachment_path)
print(mime_type)     # image/png
mime_type, mime_subtype = mime_type.split('/', 1)
print(mime_type)     # image
print(mime_subtype)  # png

with open(attachment_path, 'rb') as ap:
    message.add_attachment(ap.read(),
                           maintype=mime_type,
                           subtype=mime_subtype,
                           filename=os.path.basename(attachment_path))
print(message)

import smtplib
mail_server = smtplib.SMTP_SSL('smtp.example.com')
mail_server.set_debuglevel(1)
import getpass
mail_pass = getpass.getpass('Password? ')
mail_server.login(sender, mail_pass)     # (235, b'2.7.0 Accepted')
# Sending your message
mail_server.send_message(message)
mail_server.quit()


""" Generating PDFs """
fruit = {
  "elderberries": 1,
  "figs": 1,
  "apples": 2,
  "durians": 3,
  "bananas": 5,
  "cherries": 8,
  "grapes": 13
}
from reportlab.platypus import SimpleDocTemplate
report = SimpleDocTemplate("/tmp/report.pdf")
from reportlab.platypus import Paragraph, Spacer, Table, Image
from reportlab.lib.styles import getSampleStyleSheet
styles = getSampleStyleSheet()
report_title = Paragraph("A Complete Inventory of My Fruit", styles["h1"])
report.build([report_title])

table_data = []
for k, v in fruit.items():
    table_data.append([k, v])
print(table_data)   # [['elderberries', 1], ['figs', 1], ['apples', 2], ['durians', 3], ['bananas', 5], ['cherries', 8], ['grapes', 13]]
report_table = Table(data=table_data)
report.build([report_title, report_table])

from reportlab.lib import colors
table_style = [('GRID', (0,0), (-1,-1), 1, colors.black)]
report_table = Table(data=table_data, style=table_style, hAlign="LEFT")
report.build([report_title, report_table])

from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
report_pie = Pie(width=3*inch, height=3*inch)

report_pie.data = []
report_pie.labels = []
for fruit_name in sorted(fruit):
  report_pie.data.append(fruit[fruit_name])
  report_pie.labels.append(fruit_name)
print(report_pie.data)      # [2, 5, 8, 3, 1, 1, 13]
print(report_pie.labels)    # ['apples', 'bananas', 'cherries', 'durians', 'elderberries', 'figs', 'grapes']
report_chart = Drawing()
report_chart.add(report_pie)
report.build([report_title, report_table, report_chart])


""" submit code """
#!/usr/bin/env python3

import json
import locale
import sys
import reports
import emails
import os

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
  max_sale = {"total_sales": 0}
  for item in data:
    if item['total_sales'] > max_sale["total_sales"]:
        max_sale = item
    # TODO: also handle most popular car_year

  max_year = {}
  for item in data:
    if item['car']['car_year'] not in max_year:
        max_year.update({item['car']["car_year"]: item["total_sales"]})

    elif item['car']["car_year"] in max_year:
        max_year[item['car']['car_year']] += item["total_sales"]

  max_year_make = max(max_year.values())
  temp_year_dict = {v: k for k, v in max_year.items()}

  summary = [
      "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
      "The {} had the most sales: {}".format(format_car(max_sale["car"]), max_sale["total_sales"]),
      "The most popular year was {} with {} sales.".format(temp_year_dict[max_year_make], max_year_make)
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report
  table_data = cars_dict_to_table(data)
  reports.generate("/tmp/cars.pdf","Sales summary for last month", summary[0]+"<br/>"+summary[1]+"<br/>"+summary[2]+"<br/>", table_data)
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = summary[0] + "\n" + summary[1] + "\n" + summary[2]
  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  emails.send(message)
  # TODO: send the PDF report as an email attachment


if __name__ == "__main__":
  main(sys.argv)



